server: 
  port: 8081
spring:
  application: 
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/productDB
    username: root
    password: Alialiali1573
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}


